server:
  port: 9100
  contextPath: /search


activemq:
  broker-url: tcp://localhost:61616
  queue:
    renteCreated: dossiers.q

elasticsearch:
  clustername: elasticsearch
  host: localhost
  port: 9300
